### PR TITLE
[enhancement] Hole UI 改进

### PR DESCRIPTION
**Pull request by ivanfei-1**

### CODE REVIEW

**Comment by singularity-s0** [comment]
I suggest squashing these into 1 commit before merging, since most commits are doing the same thing and the extra ones are mainly fixing bugs.

**Comment by singularity-s0** [comment]
image
Too much margin on top, both between tag and title, and between tag and first floor.

**Comment by singularity-s0** [comment]
image

The rectangle in latest reply preview should be left-aligned with the text above.

**Comment by singularity-s0** [comment]
image

Tag overflow in folded posts

**Review by singularity-s0 — CHANGES_REQUESTED** [review]
See comments

**Comment by singularity-s0** [comment]
> > image Too much margin on top, both between tag and title, and between tag and first floor.
> 
> The extra spacing at the top of `List` cannot be adjusted within SwiftUI. You are welcomed to propose a solution to fix this.

In this case, we should at least fix the margin between tag and first floor.

**Comment by ivanfei-1** [comment]
> image
> The rectangle in latest reply preview should be left-aligned with the text above.

This padding is an intended behavior.

**Pull request merged**
